# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de8a507ad232ccad16d2b0cc66caaefcc95082fec086d0f7abb4b7eba0b21e376b140cf0d0c6b78b948d0df4cf94bb1596d4a9ed1d4791ac188dd7f3597c5cd6

test:
  secret_key_base: 2223d82a1741b13f124373d7146881bae7989fab1e6ef07e8e9ee4d9e7ad4eb0ca71bb099f4f4bf8817e2dc470d95cfd43ade4ee984720d5b1d83938f1734d98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
